#!/usr/bin/python3

import sys
import wsl

if __name__ == '__main__':
    schemafile = None

    args = sys.argv[1:]
    if len(args) >= 2 and args[0] == '--schema-file':
        schemafile = args[1]
        args = args[2:]
    if args:
        raise Exception('Unconsumed arguments:', args)

    if schemafile:
        with open(schemafile, 'rb') as f:
            schemalines = f.readlines()
        schema = wsl.parse_schema(schemalines)
    else:
        schema = None

    db = wsl.parse_db(sys.stdin.buffer, schema=schema)
    db.check_referential_integrity()

    for line in db.dump():
        sys.stdout.buffer.write(line)
