#!/usr/bin/python3

import sys
import wsl

if __name__ == '__main__':
    schemafile = None

    args = sys.argv[1:]
    if len(args) >= 2 and args[0] == '--schema-file':
        schemafile = args[1]
        args = args[2:]
    if args:
        print('Unconsumed arguments', args, file=sys.stderr)
        sys.exit(1)

    if schemafile:
        with open(schemafile, 'rb') as f:
            schemastring = f.read()
    else:
        schemastring = None

    lines = iter(sys.stdin.buffer)
    schema, tables = wsl.parse_db(lines, schemastring, datatype_parsers=None)

    problems = wsl.check_integrity(schema, tables)
    for x in problems:
        print('Integrity error:', x)
    if len(problems) == 0:
        txt = wsl.format_db(schema, tables, inline_schema=True)
        sys.stdout.buffer.write(txt)
        sys.stdout.buffer.flush()
